name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Flutter pub get
      run: flutter pub get

    - name: Accept Android licenses
      run: yes | sdkmanager --licenses || true

    - name: Build APK
      run: flutter build apk --debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
